Update pmytd
Added support to download videos in 4K-1080P
Improved audio only download function
Suppressed youtube-dl warnings
Added some more info to the Help function

diff --git a/pmytd b/pmytd
--- a/pmytd
+++ b/pmytd
@@ -14,10 +14,7 @@ exit 0
 }
 
 function HelP (){
-printf "\033c"
-grnn=$'\e[1;32m'
-endd=$'\e[0m'
-printf "%s\n" "Having problems downloading videos?" "" "YouTube and other video sharing sites" "continually change their APIs so it's" "advised to keep youtube-dl updated to" "the latest available version. You can" "check for updates from the PMYTD MENU" "by running 'Check for updates' option" "" "" "Is YouTube the only supported site?" "" "You can view the complete list of all" "supported video sharing websites here" "${grnn}https://is.gd/ytdl_supported_websites${endd}" "" "" "Press 'q' to return to PMYTD MENU" "" | less -r
+printf "%s\n" "Having problems downloading videos?" "" "YouTube and other video sharing sites" "continually change their APIs so it's" "advised to keep youtube-dl updated to" "the latest available version. You can" "check for updates from the PMYTD MENU" "by running 'Check for updates' option" "" "" "Is YouTube the only supported site?" "" "PMYTD is built with YouTube in mind" "So at present PMYTD is YouTube only" "" "" "Why can't I get videos in 4K-1080P?" "" "If your system doesn't have either," "FFmpeg or Libav installed you won't" "be able to download videos in their" "highest available resolutions. 720P" "is the highest resolution available" "without FFmpeg or Libav. To be able" "to download videos in 4K-1080P, you" "need to open your package manager &" "install either the package 'ffmpeg'" "or the package 'libav-tools'. There" "is no need to install both of these" "packages. Hint : We prefer 'ffmpeg'" "" "" "Why can't I play my 4K-1080P video?" "" "You will need a decent computer for" "playing 4K-1080P videos. Check that" "your hardware is capable of playing" "4K-1080P videos. If the hardware is" "adequate then make sure that driver" "for the graphics card is up-to-date" "Also you'll need a good software to" "play 4K-1080P videos. We prefer mpv" "on Linux, MPC-HC on Windows and mpv" "on OS X. In our experience mplayer2" "and VLC both have issues on playing" "4K-1080P videos copied from YouTube" "" "" "Press 'q' to return to PMYTD MENU" "" | less -RM
 MenU
 }
 
@@ -145,6 +142,38 @@ MenU
 fi
 fi
 printf "\033c"
+type ffmpeg >/dev/null 2>&1
+RETVAL=$?
+if [[ "$RETVAL" == 0 ]]; then
+ffmpeg -encoders | grep libmp3lame >/dev/null 2>&1
+RETVAL=$?
+if [[ ! "$RETVAL" == 0 ]]; then
+printf "\033c"
+echo -e ""
+echo -e "MP3 encoding library \"libmp3lame\" not found"
+echo -e "Install the package \"lame\" via package manager"
+echo -e ""
+read -rsp $'Press any key to return to PMYTD MENU...\n' -n1
+MenU
+fi
+fi
+printf "\033c"
+type avconv >/dev/null 2>&1
+RETVAL=$?
+if [[ "$RETVAL" == 0 ]]; then
+avconv -encoders | grep libmp3lame >/dev/null 2>&1
+RETVAL=$?
+if [[ ! "$RETVAL" == 0 ]]; then
+printf "\033c"
+echo -e ""
+echo -e "MP3 encoding library \"libmp3lame\" not found"
+echo -e "Install the package \"lame\" via package manager"
+echo -e ""
+read -rsp $'Press any key to return to PMYTD MENU...\n' -n1
+MenU
+fi
+fi
+printf "\033c"
 printf "%s\n" "" "Enter the youtube playlist link: " ""
 read -r link
 ytlnk1="https://www.youtube.com/playlist?list="
@@ -161,7 +190,7 @@ wget --spider --user-agent="Mozilla/5.0 Gecko/20100101" --timeout=30 -q "$ytlnk"
 RETVAL=$?
 if [[ "$RETVAL" == 0 ]]; then
 printf "\033c"
-youtube-dl --continue --youtube-skip-dash-manifest --yes-playlist --ignore-errors --console-title --extract-audio --audio-format "mp3" --audio-quality 0 --output "/home/$USER/Downloads/%(title)s.%(ext)s" "$ytlnk" --restrict-filenames || { printf "\033c"; echo -e ""; echo -e "Video download has failed, Something went wrong!"; echo -e "Make sure the internet connection is up & active"; echo -e ""; read -rsp $'Press any key to return to PMYTD MENU...\n' -n1; MenU; }
+youtube-dl --ignore-config --continue --console-title --no-warnings --user-agent "Mozilla/5.0 Gecko/20100101" --no-check-certificate --youtube-skip-dash-manifest --yes-playlist --ignore-errors --format bestaudio/best --extract-audio --audio-format "mp3" --audio-quality 0 --output "/home/$USER/Downloads/%(title)s.%(ext)s" "$ytlnk" --restrict-filenames || { printf "\033c"; echo -e ""; echo -e "Audio download has failed, Something went wrong!"; echo -e "Make sure the internet connection is up & active"; echo -e ""; read -rsp $'Press any key to return to PMYTD MENU...\n' -n1; MenU; }
 echo -e ""
 read -rsp $'Press any key to return to PMYTD MENU...\n' -n1
 MenU
@@ -205,13 +234,7 @@ case "$RETVAL" in
 printf "\033c"
 wget --spider --user-agent="Mozilla/5.0 Gecko/20100101" --timeout=30 -q "$ytlnk" -O /dev/null
 RETVAL=$?
-if [[ "$RETVAL" == 0 ]]; then
-printf "\033c"
-youtube-dl --continue --youtube-skip-dash-manifest --yes-playlist --ignore-errors --console-title --output "/home/$USER/Downloads/%(title)s.%(ext)s" "$ytlnk" --restrict-filenames || { printf "\033c"; echo -e ""; echo -e "Video download has failed, Something went wrong!"; echo -e "Make sure the internet connection is up & active"; echo -e ""; read -rsp $'Press any key to return to PMYTD MENU...\n' -n1; MenU; }
-echo -e ""
-read -rsp $'Press any key to return to PMYTD MENU...\n' -n1
-MenU
-else
+if [[ ! "$RETVAL" == 0 ]]; then
 printf "\033c"
 echo -e ""
 echo -e "Failed to get required information on playlist link"
@@ -221,6 +244,25 @@ echo -e ""
 read -rsp $'Press any key to return to PMYTD MENU...\n' -n1
 MenU
 fi
+printf "\033c"
+type ffmpeg >/dev/null 2>&1
+RETVAL=$?
+if [[ ! "$RETVAL" == 0 ]]; then
+type avconv >/dev/null 2>&1
+RETVAL=$?
+if [[ ! "$RETVAL" == 0 ]]; then
+printf "\033c"
+youtube-dl --ignore-config --continue --console-title --no-warnings --user-agent "Mozilla/5.0 Gecko/20100101" --no-check-certificate --youtube-skip-dash-manifest --yes-playlist --ignore-errors --format best --output "/home/$USER/Downloads/%(title)s.%(ext)s" "$ytlnk" --restrict-filenames || { printf "\033c"; echo -e ""; echo -e "Video download has failed, Something went wrong!"; echo -e "Make sure the internet connection is up & active"; echo -e ""; read -rsp $'Press any key to return to PMYTD MENU...\n' -n1; MenU; }
+echo -e ""
+read -rsp $'Press any key to return to PMYTD MENU...\n' -n1
+MenU
+fi
+fi
+printf "\033c"
+youtube-dl --ignore-config --continue --console-title --no-warnings --user-agent "Mozilla/5.0 Gecko/20100101" --no-check-certificate --youtube-skip-dash-manifest --yes-playlist --ignore-errors --format bestvideo+bestaudio/best --output "/home/$USER/Downloads/%(title)s.%(ext)s" "$ytlnk" --restrict-filenames || { printf "\033c"; echo -e ""; echo -e "Video download has failed, Something went wrong!"; echo -e "Make sure the internet connection is up & active"; echo -e ""; read -rsp $'Press any key to return to PMYTD MENU...\n' -n1; MenU; }
+echo -e ""
+read -rsp $'Press any key to return to PMYTD MENU...\n' -n1
+MenU
 ;;
 *)
 printf "\033c"
@@ -257,6 +299,38 @@ MenU
 fi
 fi
 printf "\033c"
+type ffmpeg >/dev/null 2>&1
+RETVAL=$?
+if [[ "$RETVAL" == 0 ]]; then
+ffmpeg -encoders | grep libmp3lame >/dev/null 2>&1
+RETVAL=$?
+if [[ ! "$RETVAL" == 0 ]]; then
+printf "\033c"
+echo -e ""
+echo -e "MP3 encoding library \"libmp3lame\" not found"
+echo -e "Install the package \"lame\" via package manager"
+echo -e ""
+read -rsp $'Press any key to return to PMYTD MENU...\n' -n1
+MenU
+fi
+fi
+printf "\033c"
+type avconv >/dev/null 2>&1
+RETVAL=$?
+if [[ "$RETVAL" == 0 ]]; then
+avconv -encoders | grep libmp3lame >/dev/null 2>&1
+RETVAL=$?
+if [[ ! "$RETVAL" == 0 ]]; then
+printf "\033c"
+echo -e ""
+echo -e "MP3 encoding library \"libmp3lame\" not found"
+echo -e "Install the package \"lame\" via package manager"
+echo -e ""
+read -rsp $'Press any key to return to PMYTD MENU...\n' -n1
+MenU
+fi
+fi
+printf "\033c"
 printf "%s\n" "" "Enter the youtube video link: " ""
 read -r link
 ytlnk1="https://www.youtube.com/watch?v="
@@ -273,7 +347,7 @@ wget --spider --user-agent="Mozilla/5.0 Gecko/20100101" --timeout=30 -q "$ytlnk"
 RETVAL=$?
 if [[ "$RETVAL" == 0 ]]; then
 printf "\033c"
-youtube-dl --continue --youtube-skip-dash-manifest --no-playlist --console-title --extract-audio --audio-format "mp3" --audio-quality 0 --output "/home/$USER/Downloads/%(title)s.%(ext)s" "$ytlnk" --restrict-filenames || { printf "\033c"; echo -e ""; echo -e "Video download has failed, Something went wrong!"; echo -e "Make sure the internet connection is up & active"; echo -e ""; read -rsp $'Press any key to return to PMYTD MENU...\n' -n1; MenU; }
+youtube-dl --ignore-config --continue --console-title --no-warnings --user-agent "Mozilla/5.0 Gecko/20100101" --no-check-certificate --youtube-skip-dash-manifest --no-playlist --format bestaudio/best --extract-audio --audio-format "mp3" --audio-quality 0 --output "/home/$USER/Downloads/%(title)s.%(ext)s" "$ytlnk" --restrict-filenames || { printf "\033c"; echo -e ""; echo -e "Audio download has failed, Something went wrong!"; echo -e "Make sure the internet connection is up & active"; echo -e ""; read -rsp $'Press any key to return to PMYTD MENU...\n' -n1; MenU; }
 echo -e ""
 read -rsp $'Press any key to return to PMYTD MENU...\n' -n1
 MenU
@@ -329,18 +403,32 @@ read -r choice
 case $choice in
 01 | 1)
 printf "\033c"
-youtube-dl --continue --youtube-skip-dash-manifest --no-playlist --console-title --format best --output "/home/$USER/Downloads/%(title)s.%(ext)s" "$ytlnk" --restrict-filenames || { printf "\033c"; echo -e ""; echo -e "Video download has failed, Something went wrong!"; echo -e "Make sure the internet connection is up & active"; echo -e ""; read -rsp $'Press any key to return to PMYTD MENU...\n' -n1; MenU; }
+type ffmpeg >/dev/null 2>&1
+RETVAL=$?
+if [[ ! "$RETVAL" == 0 ]]; then
+type avconv >/dev/null 2>&1
+RETVAL=$?
+if [[ ! "$RETVAL" == 0 ]]; then
+printf "\033c"
+youtube-dl --ignore-config --continue --console-title --no-warnings --user-agent "Mozilla/5.0 Gecko/20100101" --no-check-certificate --youtube-skip-dash-manifest --no-playlist --format best --output "/home/$USER/Downloads/%(title)s.%(ext)s" "$ytlnk" --restrict-filenames || { printf "\033c"; echo -e ""; echo -e "Video download has failed, Something went wrong!"; echo -e "Make sure the internet connection is up & active"; echo -e ""; read -rsp $'Press any key to return to PMYTD MENU...\n' -n1; MenU; }
+echo -e ""
+read -rsp $'Press any key to return to PMYTD MENU...\n' -n1
+MenU
+fi
+fi
+printf "\033c"
+youtube-dl --ignore-config --continue --console-title --no-warnings --user-agent "Mozilla/5.0 Gecko/20100101" --no-check-certificate --youtube-skip-dash-manifest --no-playlist --format bestvideo+bestaudio --output "/home/$USER/Downloads/%(title)s.%(ext)s" "$ytlnk" --restrict-filenames || { printf "\033c"; echo -e ""; echo -e "Video download has failed, Something went wrong!"; echo -e "Make sure the internet connection is up & active"; echo -e ""; read -rsp $'Press any key to return to PMYTD MENU...\n' -n1; MenU; }
 echo -e ""
 read -rsp $'Press any key to return to PMYTD MENU...\n' -n1
 MenU
 ;;
 02 | 2)
 printf "\033c"
-youtube-dl --console-title --list-formats "$ytlnk" | sed -e '/only/d' -e '0,/Available/d' || { printf "\033c"; echo -e ""; echo -e "Failed to get required information on video link"; echo -e "Make sure the internet connection is up & active"; echo -e ""; read -rsp $'Press any key to return to PMYTD MENU...\n' -n1; MenU; }
+youtube-dl --ignore-config --no-warnings --user-agent "Mozilla/5.0 Gecko/20100101" --no-check-certificate --youtube-skip-dash-manifest --no-playlist --list-formats "$ytlnk" | sed -e '/only/d' -e '0,/Available/d' || { printf "\033c"; echo -e ""; echo -e "Failed to get required information on video link"; echo -e "Make sure the internet connection is up & active"; echo -e ""; read -rsp $'Press any key to return to PMYTD MENU...\n' -n1; MenU; }
 printf "%s\n" "" "Enter your desired video format code from the above list: " ""
 read -r list
 printf "\033c"
-youtube-dl --continue --youtube-skip-dash-manifest --no-playlist --console-title --format "$list" --output "/home/$USER/Downloads/%(title)s.%(ext)s" "$ytlnk" --restrict-filenames || { printf "\033c"; echo -e ""; echo -e "Video download has failed, Something went wrong!"; echo -e "Make sure the internet connection is up & active"; echo -e ""; read -rsp $'Press any key to return to PMYTD MENU...\n' -n1; MenU; }
+youtube-dl --ignore-config --continue --console-title --no-warnings --user-agent "Mozilla/5.0 Gecko/20100101" --no-check-certificate --youtube-skip-dash-manifest --no-playlist --format "$list" --output "/home/$USER/Downloads/%(title)s.%(ext)s" "$ytlnk" --restrict-filenames || { printf "\033c"; echo -e ""; echo -e "Video download has failed, Something went wrong!"; echo -e "Make sure the internet connection is up & active"; echo -e ""; read -rsp $'Press any key to return to PMYTD MENU...\n' -n1; MenU; }
 echo -e ""
 read -rsp $'Press any key to return to PMYTD MENU...\n' -n1
 MenU
